# Setup
name:         Lorem IdeaEvolver Dolor Site
tagline:      Fusce pharetra egestas nisl ac lacinia 

include: ["robots.txt", "test.pdf"]

# Gems
gems:
  - jekyll-paginate
  - jekyll-sitemap

#Others
markdown: kramdown

#server options
#detach:  true
port:    4000
host:    0.0.0.0
baseurl: ""

